name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  check_pr_commits:
    name: Commit Checker
    runs-on: ubuntu-20.04

    steps:
      - name: GS Commit Message Checker

        uses: GsActions/commit-message-checker@v1
        with:
          pattern: "((feat|fix|docs|style|refactor|test|build|ci|perf)+(\\([a-z]+(.)+\\))?\\: [a-z]+(.)+)|(Review fixes(.)*)$"

          error: "One of commit messages has an incorrect title. Please read the documentation: docs/develop/pr.md."

          excludeTitle: true

          excludeDescription: true

          checkAllCommitMessages: true

          accessToken: ${{ secrets.GITHUB_TOKEN }}

  launch:
    name: Bot Launcher
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip3 install -r scripts/requirements.txt

        - name: Analysing the code with pylint
          run: |
            black --diff --color --line-length 120 sources

        - name: Run bot
          run: coverage run sources/main.py
